# Generated by Django 3.1.5 on 2021-03-04 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFaceAnalyis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('top_emotion', models.CharField(max_length=20)),
                ('second_emotion', models.CharField(max_length=20)),
                ('age_low', models.PositiveSmallIntegerField()),
                ('age_high', models.PositiveSmallIntegerField()),
                ('faces_detected_count', models.PositiveSmallIntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_analysis', to='imageais.uploadedimage')),
            ],
        ),
    ]
