# Generated by Django 3.1.5 on 2021-03-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageais', '0002_imagefaceanalyis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefaceanalyis',
            name='gender',
            field=models.CharField(max_length=2),
        ),
    ]
