# Generated by Django 3.1.5 on 2021-03-04 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imageais', '0003_auto_20210303_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagefaceanalyis',
            options={'ordering': ['face_index']},
        ),
        migrations.AddField(
            model_name='imagefaceanalyis',
            name='additional_info',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imagefaceanalyis',
            name='age_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagefaceanalyis',
            name='face_index',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagefaceanalyis',
            name='gender_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagefaceanalyis',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagefaceanalyis',
            name='top_emotion_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagefaceanalyis',
            name='age_high',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagefaceanalyis',
            name='age_low',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagefaceanalyis',
            name='faces_detected_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagefaceanalyis',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='imagefaceanalyis',
            name='second_emotion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imagefaceanalyis',
            name='top_emotion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
