# Generated by Django 3.1.5 on 2021-03-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageais', '0004_auto_20210304_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefaceanalyis',
            name='age_confidence',
        ),
        migrations.AddField(
            model_name='imagefaceanalyis',
            name='second_emotion_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
