# Generated by Django 3.1.5 on 2021-03-05 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageais', '0005_auto_20210304_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageFaceAnalyis',
            new_name='ImageFaceAnalysis',
        ),
    ]
