# Generated by Django 3.1.5 on 2021-03-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageais', '0006_auto_20210304_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='public_id',
            field=models.CharField(default='924d9305c45e', max_length=20),
        ),
    ]
