# Generated by Django 3.1.5 on 2021-03-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageais', '0007_uploadedimage_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='public_id',
            field=models.CharField(default='85bb7589ebe3', max_length=20),
        ),
    ]
