# Generated by Django 3.1.5 on 2021-03-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageais', '0008_auto_20210306_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='public_id',
            field=models.CharField(default='d42b5615c104', max_length=20),
        ),
    ]
