# Generated by Django 3.1.5 on 2021-03-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageais', '0011_auto_20210306_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='public_id',
            field=models.CharField(default='25fe808bd7c4', max_length=20),
        ),
    ]
