# Generated by Django 3.1.5 on 2021-03-06 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imageais', '0013_auto_20210306_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
