# Generated by Django 3.1.5 on 2021-04-28 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageais', '0014_auto_20210306_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(default='guest', on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
    ]
