# Generated by Django 3.1.5 on 2021-05-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageais', '0016_auto_20210428_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_name', models.CharField(blank=True, max_length=20, null=True)),
                ('object_confidence', models.FloatField(blank=True, null=True)),
                ('object_instances', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_object', to='imageais.uploadedimage')),
            ],
        ),
    ]
