# Adam Phelps 2_14_21
# docker stack deploy -c mariadb_stack.yml iais_mariadb
version: '3.3'

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASS}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080